CREATE TABLE IF NOT EXISTS aarti (
    id VARCHAR(32) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    audio_url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO aarti (id, title, audio_url) VALUES
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), '1 Aarti Jinraj Tumhari', 'https://dcn39gthlx55v.cloudfront.net/aarti/1 Aarti Jinraj Tumhari.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Aarti Shree Padam Tumhari', 'https://dcn39gthlx55v.cloudfront.net/aarti/Aarti Shree Padam Tumhari.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Aarti-Kije-Hanuman-Lala-Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Aarti-Kije-Hanuman-Lala-Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ambe-Tu-Ha-Jagdambe-Kali-Bijender-Chauhan', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ambe-Tu-Ha-Jagdambe-Kali-Bijender-Chauhan.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ambe-Tu-Hai-Jagdambe-Kali-m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ambe-Tu-Hai-Jagdambe-Kali-m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Baal-Kishan-Ji', 'https://dcn39gthlx55v.cloudfront.net/aarti/Baal-Kishan-Ji.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Baba-Balak-Nath Ji', 'https://dcn39gthlx55v.cloudfront.net/aarti/Baba-Balak-Nath Ji.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Bagulamukhi Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Bagulamukhi Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Bala-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Bala-Ji-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Batook Bhairav Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Batook Bhairav Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Bhagabat-Ji Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Bhagabat-Ji Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Bhairo Dev Aarti-Rohit', 'https://dcn39gthlx55v.cloudfront.net/aarti/Bhairo Dev Aarti-Rohit.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Bhor Bhai Thaal Sajao', 'https://dcn39gthlx55v.cloudfront.net/aarti/Bhor Bhai Thaal Sajao.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Bhuvneswari Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Bhuvneswari Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Brhamcharni Mata AartiI', 'https://dcn39gthlx55v.cloudfront.net/aarti/Brhamcharni Mata AartiI.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Brihaspativar-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Brihaspativar-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Budhvar-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Budhvar-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Chandraghanta Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Chandraghanta Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Chinnmasta Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Chinnmasta Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Chintpurni Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Chintpurni Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Dhmavati Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Dhmavati Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Durga Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Durga Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Eh Vidhi Mangal Aart Ki Jai', 'https://dcn39gthlx55v.cloudfront.net/aarti/Eh Vidhi Mangal Aart Ki Jai.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ganga Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ganga Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ganga Ram Baba Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ganga Ram Baba Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Gau-Mata-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Gau-Mata-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Gayatri-Ji-Ki-Aarti-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Gayatri-Ji-Ki-Aarti-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Gayatri-Ji-Ki-Aarti-m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Gayatri-Ji-Ki-Aarti-m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Geeta-Bhagbat Ji', 'https://dcn39gthlx55v.cloudfront.net/aarti/Geeta-Bhagbat Ji.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Giriraj Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Giriraj Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Girja Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Girja Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Gopal-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Gopal-Ji-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Gorakh-Nath-JI-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Gorakh-Nath-JI-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Govardhan-Ji-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Govardhan-Ji-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Guru-Nanak-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Guru-Nanak-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Hanuman Aarti-Govind ji', 'https://dcn39gthlx55v.cloudfront.net/aarti/Hanuman Aarti-Govind ji.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Hanuman Ji Biju', 'https://dcn39gthlx55v.cloudfront.net/aarti/Hanuman Ji Biju.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jaanki-Ji Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jaanki-Ji Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jaanki-Naath-Ji-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jaanki-Naath-Ji-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jag Janni Jay-Aarti-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jag Janni Jay-Aarti-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jag Janni Jay-m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jag Janni Jay-m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jaharveer Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jaharveer Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jai Ambe Gauri-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jai Ambe Gauri-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jai-Ganesh-Deva', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jai-Ganesh-Deva.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jai-Lakshmi-Mata', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jai-Lakshmi-Mata.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jai-Lakshmi-Ramna-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jai-Lakshmi-Ramna-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jai-Shiv-Omkara', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jai-Shiv-Omkara.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Jay jinvar Deva Swami', 'https://dcn39gthlx55v.cloudfront.net/aarti/Jay jinvar Deva Swami.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kaal-Ratri-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kaal-Ratri-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kaila Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kaila Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kalika Mata Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kalika Mata Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kamla Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kamla Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kanchan Ki Thali Laye', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kanchan Ki Thali Laye.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Katyayani Mata Aarti -Raghuvansi', 'https://dcn39gthlx55v.cloudfront.net/aarti/Katyayani Mata Aarti -Raghuvansi.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Krishna-girdhari-JI-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Krishna-girdhari-JI-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Krishna-Ji-Ki-Aarti-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Krishna-Ji-Ki-Aarti-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kunj-Vihari-Ki 2', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kunj-Vihari-Ki 2.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kunj-Vihari-Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kunj-Vihari-Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Kusmanda-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Kusmanda-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Laxhmi-Mata-Aarti-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Laxhmi-Mata-Aarti-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Laxhmi-Pati-Aarti-m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Laxhmi-Pati-Aarti-m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Maha-Gauri-Mata- Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Maha-Gauri-Mata- Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Mahaveer Ji  Ki Aarti-Pankaj', 'https://dcn39gthlx55v.cloudfront.net/aarti/Mahaveer Ji  Ki Aarti-Pankaj.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Mansa-Devi-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Mansa-Devi-Ji-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Matangi-Mata-Aarti -m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Matangi-Mata-Aarti -m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Naina-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Naina-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Naratein Aarti  Azis', 'https://dcn39gthlx55v.cloudfront.net/aarti/Naratein Aarti  Azis.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Narmada Ji Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Narmada Ji Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Om Jai Chandra Prabhu Deva', 'https://dcn39gthlx55v.cloudfront.net/aarti/Om Jai Chandra Prabhu Deva.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Om Jai Sidh Chakra Deva', 'https://dcn39gthlx55v.cloudfront.net/aarti/Om Jai Sidh Chakra Deva.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Om Jay Mahaveer Prabho', 'https://dcn39gthlx55v.cloudfront.net/aarti/Om Jay Mahaveer Prabho.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Om Jay Paras Deva', 'https://dcn39gthlx55v.cloudfront.net/aarti/Om Jay Paras Deva.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Om-Jai-Jagdish-Hare-Bijender-Chauhan', 'https://dcn39gthlx55v.cloudfront.net/aarti/Om-Jai-Jagdish-Hare-Bijender-Chauhan.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Om-Jai-Jagdish-Hare-Khushbu', 'https://dcn39gthlx55v.cloudfront.net/aarti/Om-Jai-Jagdish-Hare-Khushbu.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Om-Jai-Shiv-Omkara', 'https://dcn39gthlx55v.cloudfront.net/aarti/Om-Jai-Shiv-Omkara.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Parasuram Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Parasuram Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Parvati Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Parvati Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Pitar Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Pitar Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Pretraj-Sarkar-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Pretraj-Sarkar-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Radha-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Radha-Ji-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Raghuveer-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Raghuveer-Ji-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ram Ji Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ram Ji Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ramayan Ji Ki Aarti -Bijendra-Chauhan', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ramayan Ji Ki Aarti -Bijendra-Chauhan.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ramdev Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ramdev Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Rani-Sati-Mata-Aarti -m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Rani-Sati-Mata-Aarti -m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Ravivar-ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Ravivar-ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Sai-Baba-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Sai-Baba-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Santoshi Mata Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Santoshi Mata Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Saraswati-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Saraswati-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Satya-Narayan-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Satya-Narayan-Ji-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Seeta-Ram Ji Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Seeta-Ram Ji Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shailputri-Mata-Aarti-m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shailputri-Mata-Aarti-m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shakumbri-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shakumbri-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shanidev Aarti-Bijender-Chauhan', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shanidev Aarti-Bijender-Chauhan.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shanidev Aarti-Jai-Walia', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shanidev Aarti-Jai-Walia.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shanidev Aarti-Ravindra-Jain', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shanidev Aarti-Ravindra-Jain.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shanivar-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shanivar-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shayam Baba Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shayam Baba Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Sheetla Mata Ki Aarti-f', 'https://dcn39gthlx55v.cloudfront.net/aarti/Sheetla Mata Ki Aarti-f.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Sheetla Mata Ki Aarti-m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Sheetla Mata Ki Aarti-m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Sherawali-ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Sherawali-ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shiv Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shiv Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shodashi-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shodashi-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shri Shyam Ji ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shri Shyam Ji ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Shukravar-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Shukravar-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Sidhidatri-Mata-Aarti -m', 'https://dcn39gthlx55v.cloudfront.net/aarti/Sidhidatri-Mata-Aarti -m.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Skanda-mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Skanda-mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Somvar-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Somvar-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Surya Dev Ji Ki Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Surya Dev Ji Ki Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Tara-Rani-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Tara-Rani-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Tirpur-bhervi-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Tirpur-bhervi-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Triveni-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Triveni-Ji-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Tulsi-Mata-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Tulsi-Mata-Ki-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Veshno-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Veshno-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Vindhyanchal-Mata-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Vindhyanchal-Mata-Aarti.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Vishwakarma Ji Ki', 'https://dcn39gthlx55v.cloudfront.net/aarti/Vishwakarma Ji Ki.mp3'),
(CONCAT('ARTI', SUBSTRING(REPLACE(UUID(), '-', ''), 1, 28)), 'Yamuna-Ji-Ki-Aarti', 'https://dcn39gthlx55v.cloudfront.net/aarti/Yamuna-Ji-Ki-Aarti.mp3')